main: ${PACKAGE}.${NAME}
name: ${NAME}
version: "${VERSION}"
api-version: "1.21.4"
author: defSpaceMine
description: The SnapshotPvp Plugin!
permissions:
  permission.node:
    description: "This is a permission node"
    default: op
    children:
      permission.node.child: true
  another.permission.node:
    description: "This is another permission node"
    default: not op
commands:
  setweapon:
    description: Go to hub
    usage: "/hub"
    permission: another.permission.node
